### ISSUE TITLE
Tried but still I guess something is missing

### ISSUE THREAD

**Issue by om12nayak** [HackathonXplore15Sep/Hadoop_Code_Repo#3]
Sir I tried doing everything but still something is missing I guess.
![image](https://user-images.githubusercontent.com/35339580/94997908-e72e4000-05cb-11eb-81cb-5e076a7a1125.png)
- Getting the above error.
- Will try out some videos. Lets see. Sorry sir for unable to run .

**Comment by om12nayak** [comment]
Sir the videos are still not uploaded in the community.

**Comment by HackathonXplore15Sep** [comment]
You are getting major minor error because of the JDK version.  use jdk 8.

**Comment by HackathonXplore15Sep** [comment]
> Sir the videos are still not uploaded in the community.

can u message tat in the community the administrator will do that.

**Comment by om12nayak** [comment]
> You are getting major minor error because of the JDK version. use jdk 8.

- Is there any alternative to avoid this? Because degrading the jdk will hamper many other application in the system.

**Comment by om12nayak** [comment]
> > Sir the videos are still not uploaded in the community.
> 
> can u message tat in the community the administrator will do that.

- Have tried sir.

**Comment by HackathonXplore15Sep** [comment]
1st you can have diffreent jdk in ure system. You can map in eclipse which jdk you want for compiling. Another things you can compile in the quick start VM and jar using jar command

**Comment by HackathonXplore15Sep** [comment]
Video is posted in the community

**Comment by om12nayak** [comment]
> 1st you can have diffreent jdk in ure system. You can map in eclipse which jdk you want for compiling. Another things you can compile in the quick start VM and jar using jar command

- Sure sir I will try this, but it would be great if you can just setup the eclipse from scratch to making jar and running it. It would be really helpful, because in todays session we would be having everything downloaded and we can easily go along with you.
